version: '3.4'

services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"

  beymenwebapp:
    image: ${DOCKER_REGISTRY-}beymenwebapp
    build:
      context: .
      dockerfile: Web/BeymenWebApp/Dockerfile
